/* specinvoke config.h for cross-compilation */
#define HAVE_ERRNO_H 1
#define HAVE_FCNTL_H 1
#define HAVE_GETOPT 1
#define HAVE_GETOPT_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_MEMORY_H 1
#define HAVE_NANOSLEEP 1
#define HAVE_SELECT 1
#define HAVE_STDBOOL_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRERROR 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TIMEB_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_WAIT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_USLEEP 1
#define HAVE_WAITPID 1
#define HAVE__BOOL 1
#define STDC_HEADERS 1
#define TIME_WITH_SYS_TIME 1
#define PACKAGE_NAME "specinvoke"
#define PACKAGE_VERSION "1.0"
#define PACKAGE_STRING "specinvoke 1.0"
